In [1]:
# Cell: Analyze Cleaned Energy Data
import pandas as pd
import os

energy_dir = "energyData_clean"
file_list = [f for f in os.listdir(energy_dir) if f.endswith("_hourly_daily.csv")]

summary = []
total_rows = 0

for filename in file_list:
    path = os.path.join(energy_dir, filename)
    df = pd.read_csv(path, index_col=0, parse_dates=True)

    region = filename.split("_")[0]
    row_count = len(df)
    total_rows += row_count

    summary.append({
        "Region": region,
        "Entries": row_count
    })

# Display region-level and total summary
summary_df = pd.DataFrame(summary).sort_values("Region").reset_index(drop=True)
print(f"\nðŸ“Š Total combined entries: {total_rows}")
summary_df

ðŸ“Š Total combined entries: 45443

    Region  Entries
0      AEP     5055
1    COMED     2772
2   DAYTON     5055
3     DEOK     2407
4      DOM     4843
5      DUQ     4963
6     EKPC     1890
7       FE     2621
8       NI     2437
9      PJM     1372
10    PJME     6059
11    PJMW     5969